version: '3.1'
services:
  php:
    image: pfitzer/php-fpm
    container_name: php-fpm
    restart: always
    networks:
      - internal
      - external
    volumes:
      - ./src:/var/www/html

  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - internal
      - external
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  src:
  templates:
